### ISSUE TITLE
MANAGED_CLASS_MAPPING_ERROR when enum implement interface

### ISSUE THREAD

**Issue by cheparinV** [javers/javers#1018]
I have an interface and several enums that implement it. 
When I try to compare an object that has a field with this interface type and a value from one of the enums, I get an exception:

MANAGED_CLASS_MAPPING_ERROR: given javaClass 'class MyEnum' is mapped to PrimitiveType, expected ManagedType

**Steps To Reproduce**

1. Create Interface
2. Create enum, which implement interface
3. Create a class with a field with an interface type
4. Compare objects of this class by javers

```    
  interface TestInterface {
  }

  enum TestEnum implements TestInterface {
        FOO,
        BAR
    }

  class TestClass {
        private TestInterface enumVal;

        public TestClass(TestInterface enumVal) {
            this.enumVal = enumVal;
        }
    }

```

I have a **runnable test case**  :
https://github.com/cheparinV/javers/blob/master/javers-core/src/test/java/org/javers/core/cases/InterfaceFieldWithEnumValueCase.java

**Javers' Version**
5.11.2

**Comment by bartoszwalacik** [comment]
Interesting, thanks for the good report

**Comment by bartoszwalacik** [comment]
Javers can't managed the case when static JaversType (property type) is far different than runtime JaversType of a property value.

Here you have the property:

`private TestInterface enumVal;` 

Since it's the interface, and there are no any hints, Javers maps `TestInterface` to `ValueObjectType`.

But in runtime, you give the Enum here, which is always mapped to `PrimitiveType` in Javers.

To make it work, map `TestInterface` to `ValueType` which is close enough to `PrimitiveType`:


```
    Field ValueType:TestInterface enumVal, declared in TestClass
```
