### ISSUE TITLE
Javers Feature Request: Overload commit logic to accept EntityDefinition parameter

### ISSUE THREAD

**Issue by CalderWishneLG** [javers/javers#1284]
My company uses Spring Data Neo4j, and it has become a fairly common practice to retrieve nodes with some or none of their relationships. Fetching the entire connected subgraph, as the default `findById` repo method does, is often unnecessary and inefficient. We would like to use Javers for auditing, but this poses a problem. When we commit nodes that were fetched from the database without all of their relationships to begin with, Javers' interpretation is that the missing relationships were removed. The `@DiffIgnore` annotations don't solve this problem because the configuration they create is static - I can't ignore different fields in the same class for different use-cases. 

Ideally there would be an overloaded `Javers::commit` method like the following to accept configuration data independent of the actual object to be committed:

```
Commit commit(String author, Object currentVersion, EntityDefinition currentVersionConfig);
``` 

Is this feature something the Javers community would consider? If not, we're contemplating making the change ourselves and submitting a PR. Can someone speak to the potential level of effort involved, and whether this idea makes sense at all? Thanks!

**Comment by bartoszwalacik** [comment]
Hi @CalderWishneLG , the feature you have described is not currently wanted by the community.
Did you consider using dynamic version of `DiffIgnore` -- which is `JaversBuilder.registerEntity()` ?
The design you proposed is too simplistic, because a commit can contain objects of different classes. So it should be more like this:

```
Commit commit(String author, Object currentVersion, List<EntityDefinition> currentVersionConfig);
```

Implementing this would non-trivial, because in a Javers instance, there is a single stateful repoository -- TypeMapperEngine, which keeps all java-to-javers type mappings. Adding support for multiple TypeMapperEngines would be a huge refactoring in Javers core. In practice, it's much easier to create multiple instances of Javers, and that's a solution is already available to you.
Pleas let me know if it works for you.
