### ISSUE TITLE
Feature request: compare lists

### ISSUE THREAD

**Issue by tchegito** [javers/javers#177]
Following previous issue ( https://github.com/javers/javers/issues/176 ), here is 

When we compare directly collections with Javers, content type can't be determined at runtime.
So a way to achieve this would be this method signature:

compareCollections(Object left, Object right, Class itemType)

Then we could take advantage of Javers entities, and get a complete comparison, as if we provided a container with such list.

**Comment by kalarani** [comment]
+1
Right now i'm working around this by using a `Wrapper` class, which has no business value, and is required only for the purpose of comparison. It would be great if we can just compare two collections like
`compare(List<itemType> left, List<itemType> right)`
instead of
`compare(new Wrapper(left), new Wrapper(right))`

**Comment by bartoszwalacik** [comment]
we are working on this issue ... stay tuned

**Comment by bartoszwalacik** [comment]
released in 1.3.20

**Comment by bartoszwalacik** [comment]
see http://javers.org/documentation/diff-examples/#compare-collections

**Comment by tchegito** [comment]
Thanks, guys !
