### ISSUE TITLE
Javers-Spring Integration : Can't delete object not found error

### ISSUE THREAD

**Issue by satya-j** [javers/javers#214]
I see below error while trying to delete an entity from screen.
"nested exception is JaversException: CANT_DELETE_OBJECT_NOT_FOUND JaVers runtime error - failed to delete object"

Scenario: If I create a new entity and update/delete it, it's working fine. but If I try to delete an existing entity it's throwing the above error.

Is there a way Javers can captures(ignores if the snapshot exists already) the snapshots of all existing entities.

Correction : If I update an existing entity and then delete is working, direct delete wouldn't work.

**Comment by bartoszwalacik** [comment]
Please push a failing test which reproduces this case, you can do it on your forked Javers repository

**Comment by deepu105** [comment]
@bartoszwalacik some more details on this.

The issue is below I guess

we have some tables which has data created using SQL insert scripts, so these data are not yet indexed by Javers, if we go and update the data via spring repository which has javers annotation then javers creates an index for the table and the data, but if the action is delete instead of update then it throws this error.

So is there anyway to get javers to automatically index all the data in the DB?

**Comment by bartoszwalacik** [comment]
There is no data migration tool. Generally, data migration is a rabbit hole, there is no way to do it automatically. The only way is to pass old data throught javers instance using standard Commit API, in chronological order.
`javers.commit()` and `javers.commitShallowDelete()`

imho `commitShallowDelete()` should solve your problem with deleted objects
