### ISSUE TITLE
Provide a way to force the date of the commit in DB

### ISSUE THREAD

**Issue by obigard** [javers/javers#400]
In the current Javers version, the commit date that is stored in DB is the current date of the "commit()" method call.

In the Javers class, provide a new "commit()" with a "commitDate" parameter to force this date in DB.

**Comment by bartoszwalacik** [comment]
just use http://javers.org/javadoc_2.0/org/javers/core/JaversBuilder.html#withDateTimeProvider-org.javers.common.date.DateProvider-

**Comment by evfool** [comment]
@bartoszwalacik trying to achieve the same thing as requested here, use a commitDate property of the object just being persisted. DateTimeProvider does not receive the object properties to be able to use the commitDate property. Working around that is possible, but very hacky using ThreadLocals, and is very unsafe. Would you accept a MR for having a DateTimeProvider with an additional method, which also receives the `Map<String, String> properties` commit properties as a parameter to be able to get the commit date from the properties?

**Comment by bartoszwalacik** [comment]
What is your use case, why you need more than one `now()` ?

**Comment by evfool** [comment]
The usecase is we are doing a "backup". We periodically sync changes from a target system based on the target system log (not event-based, but periodic pull). The changes contain the timestamp the event (object change) has happened at, and we would like to use that timestamp as the commit date, as it would be correct. Currently we only have current timestamp, which means that there is a diff between real change timestamp and commitdate from javers database. Of course, we can reduce the diff by reducing the interval we do periodic syncs, but querying based on timestamp from the JaVers database will also need to be with this interval as a threshold, as we don't have exact timestamps.

**Comment by bartoszwalacik** [comment]
I can't do it, commit timestamps are used for chronological ordering. You can't set it freely, it could lead to pathology.

**Comment by stojsavljevic** [comment]
Could you please reconsider this? Here’s my use case: I have several microservices, each with its own MongoDB instance, and they communicate via RabbitMQ. I want to start auditing specific collections across these different databases. My plan was to send an event each time a relevant collection is modified, and then have a new audit component, with its own database, that listens to those events and persists changes using Javers. This approach would give me a centralized location for auditing across my entire system. However, since messages might not arrive on time, I need to use the timestamp from the event payload for accurate auditing.
