### ISSUE TITLE
ENTITY_INSTANCE_WITH_NULL_ID when using 2 databases

### ISSUE THREAD

**Issue by anhtuanluu36** [javers/javers#436]
I have the issue ENTITY_INSTANCE_WITH_NULL_ID: Found Entity instance 'com.demo.model.Unit_$$_jvst8bd_2e' with null idProperty 'id' when I store data in Postgres and I store javers in MongoDB

**Comment by bartoszwalacik** [comment]
This is not a JaVers bug. Question about ENTITY_INSTANCE_WITH_NULL_ID are recurring, please ask this question on http://stackoverflow.com/questions/tagged/javers , we will answer there.
But describe your use case a bit more, are you using Hibernate?

**Comment by evenh** [comment]
@anhtuanluu36: Some information on your configuration with multiple databases would be appreciated. Seems like the StackOverflow conversation is dead, based on the unanswered question by Paulo Galdo Sandoval.

My use case would be using a Hibernate/JPA/Spring (with transactions) for persistence of my domain objects and storing audit information in MongoDB. I haven't been able to see this use case in the official documentation.

**Comment by bartoszwalacik** [comment]
Could you link this dead StackOverflow question? I'm trying to answer all of them ...

In your case you can simply use Javers with MongoRepository, here is the Spring Config example 
http://javers.org/documentation/spring-integration/#auto-audit-example-mongo

But in this setup, a transaction rollback on SQL database wouldn't  remove corresponding audit data from MongoRepository. Both databases could diverge ...

**Comment by evenh** [comment]
I updated my comment to include the StackOverflow question. Is there any supported way to only write audit data to MongoDB if the database transaction was committed?

**Comment by bartoszwalacik** [comment]
@evenh we do not support mixed databases approach. How could it work? SQL is transactional and Mongo is non transactional. What you can do is to commit your SQL transaction first and then, when succeded, commit changed objects to Javers MongoRepository.

I can imagine a feature in javers (lets call it deferred/conditional commit), when enabled, javers would store javers commits in some in-memory queue, and would flush them to javers database only when triggered by an application message (application db commit).
But we don't plan to implement this because it looks like a corner case.
