### ISSUE TITLE
Is it possible to register ValueObject JSON Type Adapter?

### ISSUE THREAD

**Issue by wcchristian** [javers/javers#496]
I currently have an entity that one of its members is an object that has a map. I would like to write a custom json serializer so that javers stores this information simply as key value pairs and not an object that has a map.

Is there a way of adding a JSON type adapter to a valueObject or an Entity rather than just a value?

**Comment by bartoszwalacik** [comment]
No if you are using JaVersRepository, because JaVers doesn't serialize Entities but their Snapshots (objects of type CdoSnapshot). So custom JSON serializer for whole Entity would be pointless. 
You can still just take javers.jsonConverter and serialize antything, is this your case?

Maybe you can change serialization only for this 'object with a map'? Can it implement the Map interface? 

Please give more info about your case.

**Comment by wcchristian** [comment]
I think this answers my question. To elaborate, I have an object that is an entity. On that object, one of the members is another object that contains a map. Instead of adding a snapshot with the map, I would like to simply add a snapshot that consists of the key, value pairs of the map. i.e.

`{
    "foo":"bar",
    "num":123
}`

I think it would also be worth while for the user to be able to wrap JsonConverter to form their own methods of serialization. I could see how this may be an issue for the diff in javers. Just an idea.

**Comment by bartoszwalacik** [comment]
in JaVers 3.1 you will be able to register advanced JSON type adapters, maybe this will help. Stay tuned

```
  /**
  * For complex structures like Multimap
  * @since 3.1
  */
public JaversBuilder registerJsonAdvancedTypeAdapter(JsonAdvancedTypeAdapter adapter) {
     jsonConverterBuilder().registerJsonAdvancedTypeAdapter(adapter);
     return this;
}
```
