### ISSUE TITLE
Sync problem between maven central and jcenter

### ISSUE THREAD

**Issue by regrog** [javers/javers#503]
Hi,
I'm using jcenter in my gradle build to download javers and I noticed that the metadata xml file is out of sync in jcenter with available versions in the repository. Version 3.0.0 is in the repo, but it's not listed in maven-metadata.xml as you can see here: https://jcenter.bintray.com/org/javers/javers-core/

Or as you can see here, not all versions are listed in the metadata file, but only the latest: https://jcenter.bintray.com/org/javers/javers-persistence-sql/

I hope this is the right place to ask about this kind of issue.

Thanks

**Comment by bartoszwalacik** [comment]
Hi, issue already reported, there is a problem with our bintray account. JFrog team is working
on fixing the issues we are having.

**Comment by bartoszwalacik** [comment]
Unfortunately, jfrog bintray team didn't resolve this issue for seven days since reporting. They don't have any SLA in this case and they can't say when JCenter sync will be fixed for JaVers repository.

Publishing to JCenter seems now pointless to me.
Starting from 3.0.2, JaVers artifacts will be published only to Maven Central
