### ISSUE TITLE
JQL class not found @ShallowReference

### ISSUE THREAD

**Issue by croffler** [javers/javers#512]
We have used Javers now for some time and the MongoDB repo we are using has classes that do not exist or have moved to another package. JQL throws an Exception when we try to query.(class not found) Is there a way to tell Javers to ignore this condition ?

Second: We have objects that have a complex graph. Since 1.4.11 we are using @ShallowReference. When we query it takes a very long time to find the snapshots for those entries before 1.4.11. Is there a way to disable the "reference" loading ?

**Comment by bartoszwalacik** [comment]
ClassNotFound exceptions are quite easy to solve. I suggest upgrading to latest version of JaVers.

Concering second question, there is no such thing as "reference" loading in JaVers. JaVers loads only snapshots. I cant see the link between @ShallowReference and repository performance since @ShallowReference means: create less snapshots.
