### ISSUE TITLE
Javers Exception Type Name not found: Javassist

### ISSUE THREAD

**Issue by soumyabanerjee** [javers/javers#544]
We recently integrated Javers in one of our projects based on Java 8. We make use of Hibernate 4.1.6 as JPA implementation.
An anomaly we observe - first Javers store snapshots for certain dependencies (entities) in a notation that contains `$$_javassist_`. 
So if my auditable entity 'com.mycompany.somemodule.ejb.Stack' has a dependency on `com.mycompany.somemodule.ejb.NFSStorage`, snapshots have references to `com.mycompany.somemodule.ejb.NFSStorage__$$_javassist_2`.
The real problem occurs when I try retrieving snapshots using javersInstance.findSnapshots(jqlQuery) where jqlQuery = QueryBuilder.byInstanceId(new Long(id), com.mycompany.somemodule.ejb.Stack.class).build();
Sometimes, snapshots are retrieve without without fuss, other times they are not and Javers throws an exception 
`Javers Exception Type Name not found: type name com.mycompany.somemodule.ejb.NFSStorage__$$_javassist_2 not found`.
I noticed if I restart Tomcat (sometimes several times), the issue does not happen. If it doesn't happen, it stays that way!
Is this a known issue in Javers or has anyone else ran in to this before ever?

**Comment by soumyabanerjee** [comment]
Relevant snippets from the class.

`@Entity
@Table(name = "E2PD_SSP_STACK")
public class SSPStack {
private static final Logger log = Logger.getLogger(SSPStack.class);
private WebProxy formWebProxy;
private WebProxy certWebProxy;
private DBSchema schema;
private NFSStorage nfsStorage;
....

@ShallowReference
	@ManyToOne(optional = true, fetch = FetchType.LAZY)
	@JoinColumn(name = "NFSSTORAGE_ID")
	public NFSStorage getNfsStorage() {
		return this.nfsStorage;
	}

	public void setNfsStorage(NFSStorage nfsStorage) {
		this.nfsStorage = nfsStorage;
	}
....
}
`

**Comment by bartoszwalacik** [comment]
If you see `javassist` or `cglib` in the class name, it means that it's a dynamic proxy, which Hibernate generates to support lazy loading. You should not commit these objects to JaVers, because they contain a lot of junk.

Javers comes with `Hibernate unproxy hook` http://javers.org/documentation/spring-integration/#hibernate-unproxy-hook which unwraps your original domain objects from Hibernate junk.
Enable it. If you want to simplify your Javers setup, take our Spring Boot Starter http://javers.org/documentation/spring-boot-integration/ , it gives you recommended configuration out of the box (with this hook enabled).
