### ISSUE TITLE
Compatibility issue with JDK "1.6.0_27"

### ISSUE THREAD

**Issue by vamc0** [javers/javers#75]
Hi,

I am having issues using Javers with version "1.6.0_27". Also I was checking if I could build my own javers library compiled with this version even that failed as there were internal dependencies with higher version. 

Can you please let me know if this library works for the JDK version "1.6.0_27"

Thanks,
Vamsi Krishna

**Comment by bartoszwalacik** [comment]
I'll check this

**Comment by bartoszwalacik** [comment]
well, looks like that I cant compile Javers to targetCompatibility = 1.6 without changing also sourceCompatibility to 1.6
It wouldn't be easy for us, because we use Java 7 language features like <> operator.

Normally, I use Java8. Since Javers is a library, it should support older Java version. But Java 6  would be 2 steps backward. Java 7 was released on July 2011.

So, sorry I cant help you (I'll update http://javers.org/documentation/ with info that javers requires Java7 or higher). Please try to update your Jvm's instead
