### ISSUE TITLE
Mongo filter by commit ids not working when commitId has minorId higher than 0

### ISSUE THREAD

**Issue by tomashegi21** [javers/javers#970]
Hi.
I'm facing issue when trying to findChanges using withCommitIds filter.

Assuming, that there are such a commits with ids 167.01 and 166.00

Example:
`javers.findChanges(QueryBuilder.anyDomainObject().withCommitId(CommitId.valueOf("167.01")).build())` - no results

`javers.findChanges(QueryBuilder.anyDomainObject().withCommitId(CommitId.valueOf("167.1")).build())` - no results

`javers.findChanges(QueryBuilder.anyDomainObject().withCommitId(CommitId.valueOf("166.0")).build())` - returns correctly

After some investigation, I found out, that issue is caused by sending BigDecimals in  applyQueryParams method of MongoRepository.

When I override the whole repository and supply doubles insteadof BigDecimals, filtering is working as expected. 

I'm using Kotlin.

Versions:
Kotlin 1.3.70
SpringBoot 2.2.5.RELEASE
javers-spring-boot-starter-mongo 5.8.10
mongo 4.2.5

**Comment by kjheim** [comment]
@tomashegi21, we have the same issue with "167.01" and opened an issue yesterday.

Could you explain more about your solution to override the whole repository and supply doubles instead of BigDecimal.   We have also found 5.6.0 works as normal BigDecimal's but that is not a preference to move back in versions.
